### ISSUE TITLE
Extends syntax conflicts with selector grouping

### ISSUE THREAD

**Issue by sambs** [rtsao/csjs#34]
I love how standard css seems to "just work" with csjs but I've noticed an ambiguity surrounding the extends syntax and css selector grouping, due to the use of commas to separate both selectors and extend targets.

``` css
.styleA,
.styleB {
  background: red;
}

.styleA extends .baseStyle,
.styleB {
  background: red;
}
```

**Comment by rtsao** [comment]
If I'm understanding you correctly, in the latter case you are hoping for something like below?:

```javascript
{"styleA": "styleA_scoped baseStyle_scoped", "styleB_scoped": "styleB_scoped"}
```

```css
.styleA_scoped,
.styleB_scoped {
  background: red;
}
```

Where `.styleA` is a composition of `.baseStyle` and `{background: red}`, but `.styleB` is *only* `{background: red}`.

Currently, only selectors with a single class selector can extend another class, and all selectors following an `extends` is greedily treated as part of the extends. This is certainly limiting, but I think technically unambiguous albeit potentially confusing.

You could do something like this:

```css
.styleA,
.styleB {
  background: red;
}

.styleA extends .baseStyle {}
```

I'll admit this is a bit verbose.

I'm open to syntax alternatives that might be more powerful, but the current extension seems sufficient for most use cases.

**Comment by sambs** [comment]
Sorry, I could've been clearer but you've got it. It's certainly something you can work around once you understand it but it seems like a tweak in syntax could remove the ambiguity. One option would be parentheses:

```css
.styleA extends (.base1, .base) {
  background: red;
}
```

Or perhaps the comma between selectors isn't necessary at all?

```css
.styleA extends .base1 .base {
  background: red;
}
```
