### ISSUE TITLE
Is it possible to use nested SASS/SCSS-like styles?

### ISSUE THREAD

**Issue by avesus** [rtsao/csjs#57]
Like here: http://www.snaptrax.org/assets/scss/_component-examples.scss

```scss
.bd-example-row {
  .row {
    margin-bottom: 1rem;

    > [class^="col-"] {
      padding-top: .75rem;
      padding-bottom: .75rem;
      background-color: rgba(86,61,124,.15);
      border: 1px solid rgba(86,61,124,.2);
    }
  }
}
```
