### ISSUE TITLE
Scoped multi-valued animations

### ISSUE THREAD

**Issue by msn0** [rtsao/csjs#69]
Hi, I have a problem with scoped, multi-valued animations. Looks like it doesn't work as expected for me. For example the following code

```css
  .foo {
    animation: keyframe-1 1s ease-in-out, keyframe-2 .5s linear;
  }
  
  .bar {
    animation-name: keyframe-1, keyframe-2;
  }
  
  @keyframes keyframe-1 {}
  @keyframes keyframe-2 {}
```
will result in 
```css
.foo_4y20Hz {
  animation: keyframe-1 1s ease-in-out, keyframe-2_4y20Hz .5s linear;
}
.bar_4y20Hz {
  animation-name: keyframe-1, keyframe-2_4y20Hz;
}
@keyframes keyframe-1_4y20Hz {}
@keyframes keyframe-2_4y20Hz {}
```
Only the last animation-name is prefixed within a declaration value.
